# Minimal Build pipeline
# This allow us to generate wheels and upload that to a feed.

name: $(BuildDefinitionName)_$(SourceBranchName)_$(BuildID)
stages:
  - stage: Build
    jobs:
      - job: RayTests
        timeoutInMinutes: 240
        cancelTimeoutInMinutes: 5
        strategy:
          matrix:
            linux_python36:
              imageName: 'ubuntu-16.04'
              python.version: '3.6'
            mac_python36:
              imageName: 'macOS-10.15'
              python.version: '3.6'
        displayName: Ray Tests
        pool:
          vmImage: $(imageName)
        steps:
          - task: UsePythonVersion@0
            inputs:
              versionSpec: '$(python.version)'
            displayName: 'Use Python $(python.version)'
          - script: |
              python -m pip install --upgrade pip
            displayName: 'Install dependencies'
          - task: TwineAuthenticate@1
            displayName: 'Twine Authenticate'
            inputs:
              artifactFeed: ray-feed
          - bash: |
              # Cause the script to exit if a single command fails.
              set -e

              # Show explicitly which commands are currently running.
              set -x

              echo "BUILD_BUILDID: $BUILD_BUILDID"
              VERSION_SUFIX="$(echo $BUILD_BUILDID | sed -E 's/[- ]/_/g')"
              echo "VERSION_SUFIX: $VERSION_SUFIX"
              VERSION_FILE="$BUILD_SOURCESDIRECTORY/setup.py"
              if [[ "$BUILD_SOURCEBRANCH" == *"master"* ]] || [[ "$BUILD_SOURCEBRANCH" == *"releases/"* ]]; then
                VERSION_SUFIX=".${VERSION_SUFIX}"
                echo "Release generation detected. The VERSION_SUFIX will be directly appended."
              else
                VERSION_SUFIX=".dev${VERSION_SUFIX}"
                echo "Dev Release generation detected. The VERSION_SUFIX will be prefixed with the dev tag."
              fi
              if [[ $AGENT_OS == "Darwin" ]]; then
                sed -i -e -E "s+version=(['\"])([0-9]{1}\.[0-9]{1}\.[0-9]{1})(\.dev)?[^'\"]*(['\"])+version=\1\2$VERSION_SUFIX\4+1" $VERSION_FILE
              else
                sed -ier "s+version=\(['\"]\)\([0-9]\{1\}\.[0-9]\{1\}\.[0-9]\{1\}\)\(\.dev\)\?[^'\"]*\(['\"]\)+version=\1\2$VERSION_SUFIX\4+1" $VERSION_FILE
              fi
              cat $VERSION_FILE | grep "version="

              echo "Version used:"
              cat $BUILD_SOURCESDIRECTORY/setup.py | grep "version"

              echo $PYPIRC_PATH
              cat $PYPIRC_PATH
            displayName: 'Change version'
          - script: |
              python setup.py bdist_wheel
            displayName: 'Generate Wheels'
          - script: |
              python -m twine upload -r myTestFeed --config-file $(PYPIRC_PATH) dist/*.whl
            displayName: 'Upload to ray-feed'
trigger:
  branches:
    include:
      - master
      - releases/*
pr:
  branches:
    include:
      - master
      - releases/*
